sourabhsikarwar/Scene-Movie-Platform

- src/components/Navbar/Navbar.jsx
closes #11
Fixed the signup button 
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/29349136/f56b0018-77e4-4291-8b5b-ed6c65db3069
> Fixes #11 Signup button

- src/components/Navbar/Navbar.jsx
On clicking the logo of scene, the user is redirected to to the homepage which enhances the user experience.
Closes #67
> Added OnClick functionality to logo

- src/components/Banner/MovieBanner.jsx
issue #28 
Add **scrollToTop** functionality using **useEffect**.
> Add scroll to top

- .github/ISSUE_TEMPLATE/🐛-bug-report.md
- .github/ISSUE_TEMPLATE/🪶-feature-request.md
- .github/pull_request_template.md
Closes: #76 
Created ".github" folder and added new templates under "issue_template" to report bugs and add new features.
Created file under ".github" folder and added new template for PR.
This template which you can see right now if pull request template.
|      Original       |       Bug Report        |
| ![Screenshot 2023-05-23 114446](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/119059108/cf6b32da-3728-4bed-9698-ba57efa2f207) | ![bug rep](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/119059108/3c49c480-734a-432d-98fb-62ae807ecac0) |
|      Original       |       New Feature        |
| ![Screenshot 2023-05-23 …
> [PR for #76]: Created Templates to add new feature, report bugs and pull requests.

- src/components/Login.jsx
Closes: #104
-changed the display name from 'Nirvana' to 'Scenes' in the login page
The issue is fixed and ready to be merged.
But I have a doubt: Could you share one could host this in our local system as 'npm start' does not seem to working?
> name fixed

- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
- src/components/Movies.jsx
- src/pages/Home.jsx
Closes: #100
| ![Original screenshot](link) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/62666287/ae8b49a5-8426-46fe-8bed-3b56ddb75c63) |
> fix: solve trending page's show all loading issue

- src/components/Footer.jsx
Issue reference number #116 
Clicking on footer icon navigate to Home page now.
Could you please label this under GSSOC'23.
> Footer Icon navigate to Home 

- src/components/Carousel/Similiar.jsx
- src/components/Movies.jsx
Solve both the loading data issue and the trending page's not showing data issue as there was a URL problem. 
Closes: #101
| ![Original screenshot](link) | ![Updated screenshot](link) |
Updated trending page
> fix: solve trending page issue and loading problem issue

- src/components/Login.jsx
- src/components/Navbar/Navbar.jsx
- src/components/Signup.jsx
- yarn.lock
> removed login page stickiness

- src/components/Footer.jsx
Adds your GitHub account link in the footer, which makes it easier for the user to view your account.
Closes: #69 
Added functionality to your GitHub handle in the footer.
> Added your GitHub link in footer

- src/components/Login.jsx
- src/components/Signup.jsx
Closes: #133 
I have added validation for every inputs in both sing-up and log-in pages. Now user have to enter real data for logging into the website
| ![Screenshot 2023-05-25 113547](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/100519291/500109ce-d18d-43d1-916e-e78ebd9bd815) | ![Screenshot 2023-05-27 215357](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/100519291/c2a37a23-fd31-4ab4-b638-2aad34264a4f) |
> Added validation in login and sign-up page

- src/components/Navbar/Links.js
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/71914071/91db887c-b67a-4e5a-b131-65e57196c16a
> Genres "Music & War" are added

- package-lock.json
- package.json
- src/components/Search.jsx
- yarn.lock
The Search input box in the homw page is going outside of the view port in the mobile view with the width having 320px
Closes: #148 [BUG]: Search Input going out of the screen in the mobile view
The search input box is now not going outside of the view port
- [yes ] My code adheres to the established style guidelines of this project.
- [yes ] I have conducted a self-review of my code.
- [yes ] I have included comments in areas that may be difficult to understand.
- [ yes] I have made corresponding updates to the project documentation.
- [yes] My changes have not introduced any new warnings.
Previous version:
<br>
<br>
<br>
<br>
<br>
<br>
New Version:
<br>
<br>
<br>
<br>
<br>
<br>
> search input box responsive bug fixed

- src/components/Banner/Banner.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/General.jsx
- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
- src/components/Navbar/NavLink.jsx
- src/components/Profile.jsx
- src/components/Search.jsx
- src/pages/Home.jsx
- src/pages/Movie.jsx
- yarn.lock
There were scenarios when the same function calls are made double times, and when API's get called a loader was missing, useStates were declared but never used. I tried to fix them.
Closes: #130 
1. delete unnecessary code. 
2. add loader in api calls.
3.  Remoce multiple function calls
| ![Original screenshot](link) | ![Updated screenshot](link) |
> refactor: refactor codebase

- src/components/Cards/MovieCard.jsx
- src/components/SavedShows.jsx
- src/components/Signup.jsx
- src/context/authContext.js
all the issues have been solved regarding like functionality
follow these steps please:
1. Delete all users in firebase-console/authentication(screenshot provided below)
2.Delete Collections in firestore database(screenshot provided below)
3. restart the server by npm start in root directory
4. screenshot below(i have also added the cross button in favourite shows in favourite movies)
previous errors were occuring because of two same email id used ..
this wont be an issue in production level as google provides everyone a unique email id 
for each unique email id savedShow array is identified and stored in google firestore
screenshot below:
refer this video below
https://www.youtube.com/watch?v=ATz8wg6sg30
( from 1:48:10)
peace!
if still any problem persists then please free to ask!
> final bugs fixed resolved

- package-lock.json
- src/components/Profile.jsx
- yarn.lock
Closes: #178 
- [x ] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.
| 
| 
|
> Profile Section UI Enhancement done

- src/App.jsx
- src/components/ProtectedRoute.js
- src/context/authContext.js
Closes: #22
Added a loading state in the auth context which will be true until the user data from firebase is fetched so that the protected route does not redirect the user before the fetch is complete.
> Website Redirects to Login Page Upon Refresh solved

- src/components/Banner/MovieBanner.jsx
- src/index.css
Closes: #184 
Changed some CSS to achieve responsiveness of the youtube video that is present on the movie page and made it responsive for all devices.
> Trailer video responsiveness added

- public/index.html
- src/components/Navbar/NavLink.jsx
Closes: #196 
- Added primary, facebook, and twitter types of meta tags in the index html file.
- Added a valid key prop to the map function which removes an error from the browser console.
> Meta tags added

- src/components/Login.jsx
- src/components/Profile.jsx
- src/components/Signup.jsx
Closes: #[192]
| 
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/113853868/785a4a9b-057d-4d6a-987d-922f4adbd3e0) |
> Added show button #192

- src/components/Profile.jsx
Closes: #187 ]
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/113853868/97dabb06-47b8-409a-a52d-df7aef63bdb2) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/113853868/8536943a-e09c-47b8-a339-df18ca44027f) |
> Fixed rendering error in Date of Birth section #187

- src/components/Carousel/Trending.jsx
- src/components/Navbar/NavLink.jsx
- src/components/Navbar/Navbar.jsx
- src/pages/Home.jsx
Closes: #189 
Added key prop to all map functions which removed the error messages in the browser console.
> Added key prop

- src/components/Cards/Card.jsx
- src/components/Cards/MovieCard.jsx
- src/components/Favourite.jsx
- src/components/Profile.jsx
- src/components/Ui/Avatar.jsx
- yarn.lock
Closes: #205 
Added a valid alt attribute to all img tags.
> Alt attributes added

- .github/ISSUE_TEMPLATE/📄-Doc_report.yml
Closes: #203 
Added doc_report.yml file in issue template
> Added doc_report issue template

- .github/ISSUE_TEMPLATE/Documentation.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/styles.yml
Some additions are made to the Issue Template.
Closes: #182 
Added 3 files:-
- config.yml ( blank issue file for rasing issues that don't belong to the given issue templates )
- documentation.yml
- styles.yml
@sourabhsikarwar Thank you for this opportunity.
> Additions in Issue Template done

- src/App.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Cards/Card.jsx
- src/components/Favourite.jsx
- src/components/Footer.jsx
- src/components/Login.jsx
- src/components/Navbar/Navbar.jsx
- src/components/Profile.jsx
- src/components/SavedShows.jsx
- src/components/Signup.jsx
- src/components/Ui/Avatar.jsx
- src/pages/NotFound404.jsx
Closes: #57 
Implemented Lazy loading for all the pages and images in this project due to which whenever the website loads initially then only the content that is visible to the user are loaded instead of the whole content. This reduces the initial loading time making the user experience better.
> lazy loading implemented

- src/components/Search.jsx
-The Api was called for every key pressed while searching any movie
Closes: #208 
-Updated the search functionality in the Search Component and now less number of api calls are made while searching the movies.
> updating the search functionality

- package-lock.json
- src/components/Login.jsx
- src/components/OAuth.jsx
- src/components/Signup.jsx
- yarn.lock
Closes: #[222]
The login and signup page UI has been updated.
Created an OAuth component that displays a button CONTINUE WITH GOOGLE.
In the OAuth component, used the Firebase Google Authentication feature.
It follows the user to login/signup with a Google account, if the user exists it redirects to the home page.
If the user does not exist, it will add the user to the database and redirect to the home page.
The user can create a new Google account, if a user has no Google account.
| Original|
|Updated|
|Updated|
> [Feature] SignUp / Login In with Google Account

- src/components/Signup.jsx
Before whenever the user signs up the the user gets logged in but still navigates to the login page which is not required. So I changed the code such that whenever the user signs up he will redirect directly to the home page.
Closes: #213 
Added a timeout function which will wait for 2 seconds and then navigate to home page after signing up because it takes time for the app to add the user data to the context so if there is no timeout function then just after sign up the user will be redirected to home but the user data in the context will be null so the protected route will redirect the user to the login page again.
> Home page navigation after signing up added

- package-lock.json
- package.json
- src/App.jsx
- src/components/Login.jsx
- src/context/authContext.js
- yarn.lock
Closes: #204 
Added toast messages to login and sign up which will display whenever the corresponding action is pending, successful, or if there is an error.
> Toast messages added

- package-lock.json
- package.json
- src/components/Signup.jsx
Closes: #233
- Added country code to the phone number input .
- Changed number validation to 13 instead of 10 digits to accommodate for country code and phone number.
- Installed a new package 'react-phone-input-2'.
| ![snap22](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/110723341/c6892dae-4fe7-437f-a49e-815a04f7759e) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/110723341/1a3716cf-d0ea-4a88-a1ec-d622e9bb4e62) |
> added country code to number input

- package-lock.json
- src/components/Login.jsx
made history viewing disable for privacy of the user.
Closes: #236 
| ![Original screenshot](link) | ![Updated screenshot](link) |
> Updated Login form Issue: #236

- src/components/Login.jsx
- yarn.lock
Closes: #238 
- Changed the current default firebase error message to a custom message for better user understanding
- Added error messages like "Username or Password didn't match." and "User not found"
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/115284013/0a84876b-191b-4f00-9712-dd0eefa36c93) | 
in reset password side
and also
> changed firebase error messages to the custom one

- src/components/Signup.jsx
Closes: #239 
The regular expression for the mobile number was fixed to have 13 digits. But it varies according to country code and the no of digits of phone number of that country. I've found out that that the phone number can have a minimum of 7 digits(country code - 2 digits and mobile no - 5 digits) and a maximum of 13 digits(country code - 3 digits and mobile number - 13 digits). <br/>
So I've updated the regular expression to check for the length of digits to be in between 7 and 13.
|  ![Screenshot 2023-06-16 173728](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/83866602/a87554be-4546-4c5a-bf91-0b362ac07738)| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/a …
> Fixed Phone Number

- src/App.jsx
- src/components/ScrollToTop.jsx
- tailwind.config.js
Closes: #19 
Added a functional scroll to top button which matches the UI of the website.
> Added scroll to top button

- public/index.html
- src/App.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
- src/components/Footer.jsx
- src/components/Login.jsx
- src/components/Navbar/NavLink.jsx
- src/components/Navbar/Navbar.jsx
- src/components/Profile.jsx
- src/components/SavedShows.jsx
- src/components/Search.jsx
- src/components/Signup.jsx
- src/components/Ui/Avatar.jsx
- src/index.css
- src/pages/Home.jsx
- src/pages/NotFound404.jsx
- src/style.js
- tailwind.config.js
Closes: #9 
- Added a light mode functionality.
- User can now switch between light and dark mode using a toggle switch.
| ![Screenshot (509)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/90e65d7a-65e6-4e6a-9b2c-f557923a69e8) | ![Screenshot (510)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/c0c0d241-ffb5-44c2-a8b9-0ec08b1f1e93) |
| ![Screenshot (508)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/744d426d-aae3-4b20-9d7d-6171c698ccca) | ![Screenshot (507)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/56786344/421e6658-98b5-4b2c-bf87-0d3a03c69bfc) |
| ![Screenshot …
> Added light mode functionality

- src/components/Cards/MovieCard.jsx
Closes: #256
- I have removed the movie card from the favorites list after subsequent clicks on the favorite button!
- Updated the moviecard.jsx file to fix the bug
|      Liked      |     Unliked      |
| ![After bug - liked](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/55fd181e-f818-4233-9a66-c0c5efff0355) | ![After bug - unliked](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/dcc5b2bf-c573-4e4c-b891-1994914d1567) |
**As you can see in the above screenshots after subsequent clicks on the favourite button the movie is removed from the favourites list**
> Remove from favourites after subsequent clicks on favourite button

- src/context/authContext.js
Closes: #240 
The user details in the profile page are now fixed.
| ![Screenshot (27)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/83866602/70fecee9-a0c9-4e26-a9e9-e724c5c00dd7) | ![Screenshot (30)](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/83866602/44336f20-cc2e-422f-b0fe-c01aa535ea4f) |
> Fixed Profile

- src/components/Banner/MovieBanner.jsx
This PR is related to Issue in which due to any reasons, the watch button and like button were not visible in the website.
Closes: #270 
I have fixed the issue now. And the watch button and like button are clearly visible now!
| *Original* |
| *Updated* |
> Fixed the issue of watch and like button!

- src/App.jsx
- src/components/Login.jsx
- src/components/Reset.jsx
- src/components/Signup.jsx
Closes: #261 
- I have added a new Password reset page and checked its functionality, it's working fine.
- Updated the login.jsx and added a new reset.jsx file.
|      Updated        |
| :------------------: |
| <img width="943" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/14081d74-6744-46e6-af79-a48fa870f3b1">|
> Added the passwordReset page

- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
- src/components/Movies.jsx
- src/components/Navbar/Navbar.jsx
- src/components/Pagination.jsx
- src/pages/Home.jsx
Closes: #287 
- Added code to redirect to the home page when clicking logo of navbar.
> logo redirecting to home

- package-lock.json
- package.json
- src/components/Footer.jsx
- yarn.lock
There was no proper Footer Section on the website. It was a very basic Footer Section.
Closes: #283 
I have created a new Footer Section. In the new Footer Section, there are sections like Quick links, Social media links, and many more and now it looks professional.
| 
|
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/85991449/f2714b3f-14a7-4dd1-ac6d-54ce16f23422
|
> Fixed : issue #283

- src/App.jsx
- src/components/AdminAbout.jsx
- src/components/Contributor.jsx
- src/components/Navbar/Navbar.jsx
- src/index.css
- src/pages/About.jsx
About us page created 
mobile responsive
some info and github link for contributor
project admin 
contributors with pagination 
footer
Closes #263
> About us page

- .gitignore
- server/.gitignore
I have updated few files and which will help to run code on local devices properly without any issues of packages.
- [ x] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] I have made corresponding updates to the project documentation.
- [x ] My changes have not introduced any new warnings.
> #308 issue Resolved

- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/Trending.jsx
Closes: #302 
| <img width="960" alt="248265396-0354d05b-b1df-4726-b375-246f78f2da88" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/9c0d3476-f07a-4201-8a43-1133bb83a37f"> | <img width="960" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/a371638b-87f0-49f7-810c-075f3437cf36"> |
> fix white space

- src/components/Login.jsx
- src/components/Reset.jsx
- src/components/Signup.jsx
Closes: #265 
- I have implemented the auto scroll to top feature when clicking on the login and signup links in those pages.
- Previously the page was opening at the bottom of the window which was not good user experience
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/8a6c170d-4d6a-41c1-a523-f895c414e258
> Added auto scroll to top feature

- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/Similiar.jsx
Closes: #327 
- Before, when the user was clicking any movie of the Similar Carousel, the URL was changing but the movie content wasn't being displayed.
- Now, when the user clicks any movie of the Similar Carousel, the requested page is displayed to the user which contains the movie details and Similar Carousel.
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/9282b6c3-69d5-475a-9197-4b99811363ee
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/ecd0bee2-4236-4597-a704-56b3811e248e
> fixed movie routing issue

- public/index.html
- src/App.jsx
- src/assets/style/Footer.css
- src/components/Footer.jsx
Closes: #376 
Hello, I've successfully integrated an improved and adaptable footer that not only enhances the overall aesthetics but also effectively embodies the essence of the web application.
**Demonstration:**
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/100872683/651cd2f2-a7be-4d3e-80ab-8c10eddf58e9)| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/100872683/e02194ae-5425-4bbe-8bdf-cc73c3f89b4e)|
> Enhance the footer (Issue #376)

- src/components/SavedShows.jsx
Closes: #385 
Removed left and right scroll from favorites when there are no movies saved in favorites.
> Scroll removed from favorites when no movies saved

- src/components/Cards/GenreCard.jsx
- src/components/Carousel/Genre.jsx
- src/pages/Home.jsx
- src/style.js
Closes: #63 
Popular Genres Filter is added after the Trending section It is combined Genre card and each card direct user to the specific genres movie
<br>
<br>
**_Kindly check it and suggest if further changes need to be made.
PS.: Sorry to generate PR this late I have my exams going on so....._**
> feat: Home Page `Popular Genre` Filter added 

- src/components/AdminAbout.jsx
- src/pages/About.jsx
- src/style.js
Closes: #386 
Made about us page responsive and made some minor UI changes
> About us page made responsive

- package.json
- src/components/Cards/MovieCard.jsx
Closes: #221 
- I have implemented the share functionality of the card.
- Now the URL of the card can be shared among multiple apps listed in the below screenshot
| <img width="189" alt="Screenshot 2023-07-02 004836" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/15980d32-9bb0-4602-be52-b87632d50919"> | <img width="191" alt="Screenshot 2023-07-02 004755" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/98690105/dbed08e4-9e59-4ba1-8946-e249a3009bdd"> |
> Added share functionality to the card

- src/components/Login.jsx
- src/components/Signup.jsx
Closes: #404 
Added aria attributes like role, aria-labelby, aria-label, aria-invalid, aria-describedby to login and signup forms to improve accessibility
> Added aria attributes to login and signup forms

- server/routes/movies.js
- src/components/Banner/Banner.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Carousel/General.jsx
- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
- src/components/SavedCards.jsx
- src/components/Search.jsx
- src/helper/fetchData.js
- src/pages/Home.jsx
Convert axios into fetch
Closes: #399
| ![Original screenshot](link) | ![Updated screenshot](link) |
> feat: convert into fetch api from axios

- src/components/Footer.jsx
Closes: #405
Added aria attributes to the footer elements to enhance accessibility.
> Added accessibility to footer

- src/components/Banner/MovieBanner.jsx
- src/index.css
Closes: #269 
- Separate UI for mobile screens and other screen sizes.
- Displayed movie details
- Made it responsive.
- Dark mode compatible
- Displayed trailer properly on mobile devices
| <img  alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/ace3cbb6-5ae4-4023-9150-fde80f3f94f5"> | <img width="577" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/6628fdd4-e3e5-4715-8e54-9f6c81ea4257"> |
|<img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/4741ad53-b9c8-40c9-82b4-c2775fe507a8"> | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/c2e3097f-c509-4 …
> Movie page UI optim

- src/components/Search.jsx
Closes: #420 
- I have fixed search field input color for dark and light mode.
- I have fixed search results content for dark and light mode.
- I have fixed content visibility for dark and light mode in case of 'No result found'
| <img width="538" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/763411ce-2010-47ab-bccf-de86a1a748ff"> | <img width ="538" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/5fec7330-80dc-4621-9c63-7b7e73f0e051"> |
| <img width ="538" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/64773fb1-7a2f-4e5a-8a03-a32693f05acc"> | <img width ="538" …
> search input and result contents visibility

- src/App.jsx
- src/components/Banner/TvBanner.jsx
- src/components/Cards/Card.jsx
- src/components/Cards/MovieCard.jsx
- src/components/Carousel/Trending.jsx
- src/components/Navbar/Links.js
- src/components/Navbar/NavLink.jsx
- src/components/Navbar/Navbar.jsx
- src/components/TvShows.jsx
- src/pages/Categories.jsx
- src/pages/Home.jsx
- src/pages/Movie.jsx
- src/pages/Tv.jsx
Closes: #289 
- Added TV Shows dropdown in the navbar containing all the genres.
- Dropdown genres redirecting to the particular genre page.
- Displayed Trending TV Shows Carousel on home page.
- TV page displaying Show's details.
- Ensured it was darkmode compatible.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/cb032a4c-645c-48ea-907e-d726e24c04d4"> | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/de5b3cd9-2cb3-4bf9-869d-61b896381daa) |
| Tv Shows Dropdown | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/a3a39910-e074-4fae-ad42-338d827c6fa2">|
| Trending TV Shows | …
> Added tv shows

- src/components/Banner/MovieBanner.jsx
Closes: #348
- Added movie duration on the banner and in movie details section.
- Added release status.
- Added spoken languages
- Displayed all the genres in the details.
- Ensured that the details section was responsive.
| <img width="629" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/aa0ae27b-323a-48c2-9a17-90c4edf240e7"> | <img width="542" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/7cb759b6-0297-4d39-97d2-a8cbd48ef5e6">|
| Light mode | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/21e530fd-4610-441f-8914-7e2f3d4c018c) |
> added movie details section

- package.json
- public/index.html
- src/App.jsx
- src/components/SavedShows.jsx
Closes: #439
- Added a text chatbot
- Chatbot icon can be draggable to any place on the screen
- Users can get information about the website
- Users can also navigate to any page using the chatbot
> Added chatbot functionality

- src/components/Banner/MovieBanner.jsx
- src/index.css
Closes: #374 
- Displayed author name, review and rating.
- Displayed author images if exists else displayed default user icon.
- If the user hasn't provided any rating then the rating is not displayed.
- Added navbar to display movie details and reviews conditionally.
- Displayed 200 characters of the review and added a 'read more' link to load the whole content.
- Displayed 4 reviews and added a 'see more' button to load more reviews if present.
- Ensured responsiveness.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/97011cd3-404a-4b70-87ed-2dd177641f8c"> |<img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/2d2d6633-c58c …
> added movie reviews 

- src/App.jsx
Previously in this pr https://github.com/sourabhsikarwar/Scene-Movie-Platform/pull/463 I added the key in the env file which was only accessible to me but in this pr, I have directly added the chatbot key in the file so that everyone can access the chatbot.
> Added the chatbot key

- src/components/Banner/MovieBanner.jsx
- src/index.css
Closes: #402 
- Added movie snapshots
- Ensured responsiveness
- Darkmode compatible
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/f2d336aa-a7c6-4416-8725-868d07fed5e9"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/3251794a-51a3-4259-afe2-6b6f87a825f6"> |
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/e9d2aeb1-5a52-4a35-9f67-1632d869c628"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/45794fe4-dd61-44b6-8b88-f7292bfb95e7">|
> Movie snapshots

- src/components/Banner/Banner.jsx
Closes: #401 
- Added popular movies slider instead of single banner on home page.
| <img width="372" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/a4cc9de4-a78d-4c73-bd11-88686aa859e5"> | <img width="493" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/47386090-1e07-45a2-8126-8c8b55981f86"> |
> added slider on homepage

- src/components/Banner/MovieBanner.jsx
- src/components/Banner/TvBanner.jsx
Closes: #459 
- I have fixed the banner details alignment on movie page and tv shows page.
> fixed movie details alignment over banner

- src/components/Banner/TvBanner.jsx
Closes: #467 
- Added a section with more details of the tv show.
- Fixed banner content and color for darkmode.
- Conditional rendering to handle empty data fields.
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/16a61a70-34ff-4110-9969-63aa5ab44d9d) | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/02cd02ec-3d84-4ff7-bf1c-202d393a34c9"> |
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/43a011b8-60ab-4304-941a-26831d5ea401"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/ad9c2d40-9364-4b1a-8928-ec22b3847406"> |
Please …
> Added Tv shows details

- src/components/Banner/TvBanner.jsx
Closes: #475 
- Added reviews
- Added header to toggle between details and reviews for better UI and UX.
- Darkmode compatible
- Ensured responsiveness.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/6d6146c7-22db-4368-9343-bc18c53667a8"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/e6777f45-f233-476b-b055-381a12506a31"> |
|<img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/2c4210b6-b474-4960-a340-2700018da9d0"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/6588b4fc-5587-4cb7-87fb-d162d66a6de2">|
Please provide any …
> Tv reviews

- src/components/Navbar/NavLink.jsx
- src/components/Navbar/Navbar.jsx
Closes: #357 
- Added dropdown collapsing after clicking any link of the dropdown
https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/13bdae93-2a39-433f-8ca5-e12d07ec55f3
> added dropdown collapsing

- src/index.css
- src/pages/Home.jsx
Closes: #422 
- Added toggle button to switch between tv shows and movies.
- Added function to handle toggle button and displaying relevant content.
- Ensured responsiveness.
- Darkmode compatible
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/3ee6cf39-7187-4385-b1d6-a77771af6c64"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/ac02a1fb-6ef5-49f7-9a52-36b6e6e8ba8b"> |
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/f6c0ae5a-1e83-47a5-bbda-607ccd044617"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/757df11f-804b-4f02-94 …
> added toggle btn for tv series and movies

- src/components/Banner/TvBanner.jsx
- src/index.css
Closes: #468 
- Added all Seasons in the header
- Rendered respective episodes conditionally
- Rendered first 10 episodes and then added a see more button to render more episodes
- Ensured responsiveness
- Dark mode compatibility
| <img width="960" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/e16622ed-a09d-4f69-b20c-6ae5235f2fae"> | <img width="960" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/8a4b1b24-466b-4504-8347-b405e8508d38"> |
| <img width="485" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/58bfdd24-7344-43d7-add6-35e681f5291e">|<img width="409" alt="image" …
> Added Seasons and episodes

- src/components/Contributor.jsx
> search Feature Added #503

- src/components/Profile.jsx
- src/pages/About.jsx
Bug fix Profile alignment issue #504 
Hii @sourabhsikarwar  I have raise pr pls check and merge.
> Bug fix 504 Profile alignment issue

- src/components/Cards/MovieCard.jsx
- src/components/Carousel/Trending.jsx
- src/pages/Home.jsx
Closes: #496 
- Added Airing Today TV Series Carousel
|      |               |
| <img width="960" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/670085fb-407e-449c-ac32-520327071a2f">| ![Updated screenshot](link) |
> added airing today 

- src/components/Navbar/Navbar.jsx
- Fixed the vertically misaligned nav bar for Mobile devices.
- Additionally replaced the Inline style rules with Tailwind Utility classes to maintain Clean code.
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/92252895/231fe0e2-cd99-4942-899f-d4e66b1c4785)| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/92252895/8de326ce-99c1-4052-87c6-b948dd499f60) |
> fix: vertical misalignment of nav bar on desktop device ⚒️✨ 

- src/components/Footer.jsx
Closes: #516 
- Tv shows is not a single page content (just like movies), therefore I removed it from the footer.
> removed tv shows link from footer

- src/index.css
bug fix for the chatbot #513 
@alan-ai/alan-sdk-web  fix
> bug fix issue chatbot #513

- src/components/Profile.jsx
- src/components/styles.css
bug fix for input css issue profile page #522
> fix: input css issue profile #522

- src/components/Banner/MovieBanner.jsx
- src/index.css
Closes: #498 
- Styled and Displayed videos conditionally in a carousel.
- - [x] Responsive.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/040543dd-b47f-476c-94f7-02c80ee0206c"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/91bfafd4-bd8f-42fa-a83d-160c5773fab3">|
|<img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/4c557331-fb95-4830-b3d4-3159d5fb0195"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/6a138227-c2c3-4134-a326-2a417a0508dd">|
> Added Videos

- src/components/Banner/Details.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Banner/TvBanner.jsx
Closes: #487 
-Added Tv-series Snapshots
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/2f7eccb8-0e4d-4739-8aa8-70fd07eb28a0) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/2f7eccb8-0e4d-4739-8aa8-70fd07eb28a0) |
> Added Tv snapshots

- src/components/Banner/MovieBanner.jsx
- src/components/Cards/MovieCard.jsx
Closes: #556 
- Fixed share link url
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/51f83b3b-d24c-46eb-9939-fdcd707be4d0"> | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/560c709b-03c5-4530-a4ea-fcb5ac9060ee) |
> Share link

- src/components/Banner/Details.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Banner/TvBanner.jsx
- src/components/Carousel/Similiar.jsx
Closes: #488 
- Fixed whitespace appearing in similar component as well as details section
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/3639bdee-ef7d-4772-b279-10cd16df1bda"> | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/a5defe65-e96f-4d0b-b348-27c1552333d1) |
> Fixed Similar whitespace

- src/components/Banner/MovieBanner.jsx
- src/components/Cards/Card.jsx
Closes: #494 
- Added circular ratings on every genre page
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/8abcea53-ed58-498f-8426-9fa7f1208b89) | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/cf60e70c-5255-4970-b253-705eeada133e">|
> Added Circular rating

- src/components/Banner/CommonBanner.jsx
- src/components/Banner/MovieBanner.jsx
Closes: #489 
- Added readmore link to the movies/tv shows overview.
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/bd85f937-8643-45d7-bafc-cee048c77c81) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/b8473072-64d7-435e-9463-4c86d1f0ee60) |
> Added Readmore

- src/components/Banner/MovieBanner.jsx
- src/components/Cards/MovieCard.jsx
- src/components/Carousel/Similiar.jsx
- src/components/Carousel/Trending.jsx
Closes: #520 
- Refactored movieCard component.
> Moviecard refactor

- src/components/Navbar/NavLink.jsx
- src/index.css
- src/pages/Home.jsx
Closes: #515 
- Fixed the navbar scroll bar
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/83b979a7-beb4-44a4-aa3c-948e0935c013"> | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/7919cca0-6c93-427d-aa90-42ca89a198b7) |
> fixed scroll bar

- src/components/Banner/MovieBanner.jsx
- src/components/Banner/TvBanner.jsx
Closes: #535 
- Reduced separate requests.
- Reduced the number of separate useEffect hooks which have same dependency.
> Reduced Requests

- src/components/Banner/CommonBanner.jsx
- src/components/Banner/TvBanner.jsx
- src/components/Cards/MovieCard.jsx
- src/index.css
Closes: #554 
- Added videos tab fo particular season
> Season videos

- src/components/Cards/MovieCard.jsx
- src/components/Carousel/Trending.jsx
Closes: #519 
- I have reduced the redundancy of trending component
> refactored trending component

- src/components/Cards/MovieCard.jsx
- src/components/Search.jsx
Closes: #501 
- Handled search bar overflowing on mobile devices.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/9ade38a4-ef4c-483b-9e90-a09ba43b00a3"> | <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/8f5e9caa-9f29-4fb1-be54-e89cf7217fa1"> |
> searchbar overflow

- src/components/Banner/MovieBanner.jsx
- src/index.css
> Bug fix 547 

- src/components/Cards/Card.jsx
- src/components/Carousel/Trending.jsx
Closes: #579 
- Refactored card component
> refactored card component

- src/components/Cards/GenreCard.jsx
- src/components/Cards/MovieCard.jsx
Closes: #597 
- Fixed card onclick. Now clicking anywhere on the card will redirect to the requested page.
> fixed card onclick

- src/components/Cards/Card.jsx
Closes: #592 
- Rendered correct release dates of the TV Series on all cards
| ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/b774e970-fbe8-490b-a2f4-593af2f9382b) | ![image](https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/7d6aca98-53c7-43a1-a32a-922db7a4e9bc) |
> correct release date

- src/components/Banner/CommonBanner.jsx
- src/components/Banner/TvBanner.jsx
Closes: #577 
- Displayed TV Series Trailer
- Rendered conditional rendering (not displayed watch trailer button when there is no trailer available)
| <img width="592" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/d2269d58-d86d-4cb2-90d1-86ceae3704b9"> | <img width="960" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/f6a025a6-5fe1-47f7-817b-24eb648e4763"> |
| In case of no trailer available | <img width="579" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/142e054f-3c40-49f2-90d4-889388757eb1"> |
> Added Tv trailer

- src/components/Banner/CommonBanner.jsx
- src/components/Banner/Details.jsx
- src/components/Banner/MovieBanner.jsx
- src/components/Banner/TvBanner.jsx
Closes: #581
- Refactored TV/Movie pages and reduced redundancy
> refactored movie/tv pages

- src/App.jsx
- src/components/Banner/Episode.jsx
- src/components/Banner/TvBanner.jsx
- src/pages/Episode.jsx
Closes: #575 
- Added Episode page
- Redirecting user to the requested episode page on clicking any episode.
- Rendered relevant available details regarding the particular episode.
| <img alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/17dc0170-2896-499e-b363-8c3144c6deff"> | <img width="921" alt="image" src="https://github.com/sourabhsikarwar/Scene-Movie-Platform/assets/66116440/2bda7aa9-967d-405d-88c3-e35853f2fc7b"> |
> added episode page

- src/components/Banner/CommonBanner.jsx
- src/components/Banner/Details.jsx
- src/components/Banner/TvBanner.jsx
Closes: #601 
- Handled all empty data fields
> handled empty data fields

- src/components/Banner/Episode.jsx
Closes: #469 
- Added Next episodes
> Added Next episodes
